Repository CycloneDX/cyclonedx-property-taxonomy, pull requests merged in 2024-12, with the labels that each got.

#108 add rust-maintainers to CODEOWNERS
  CODEOWNERS
Labels: chore

#112 remove docs for TLNamespace `ksoc`
  README.md
Labels: documentation, TLN-registry

#114 Update link to OWASP Dependency-Track taxonomy
  README.md
Labels: TLN-registry

#113 Rename ksoc top level namespace to rad
  README.md
Labels: TLN-registry
